[project]
name = "azuredevops-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "azure-devops>=7.1.0b4",
    "mcp[cli]>=1.9.2",
    "python-dotenv>=1.1.0",
]
